version: '3.9'
services:
  mongo:
    container_name: mongo-container
    image: mongo:4
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - '27012:27017'
  api:
    container_name: api-container
    restart: always
    image: node
    working_dir: /usr/src/survey-api
    command: bash -c "npm install && npm run start"
    environment:
      - MONGO_URL=mongodb://mongo:27017/survey-api
    volumes:
      - ./dist/:/usr/src/survey-api/dist
      - ./package.json:/usr/src/survey-api/package.json
    ports:
      - '5050:5050'
      - '8222:8222'
    links:
      - mongo
